services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/nexus:cached
    command: tail -f /dev/null
    depends_on:
      - db

  db:
    # UPDATED LINE: Use a postgres image with pgvector pre-installed
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_USER: nexususer
      POSTGRES_PASSWORD: nexuspass
      POSTGRES_DB: nexusdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: